=begin
#<enter your title>

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 0.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::AddressAPIApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AddressAPIApi' do
  before do
    # run before each test
    @instance = SwaggerClient::AddressAPIApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AddressAPIApi' do
    it 'should create an instance of AddressAPIApi' do
      expect(@instance).to be_instance_of(SwaggerClient::AddressAPIApi)
    end
  end

  # unit tests for get_balance
  # Get Balance
  # Returns the satoshi balance, usd balance and user viewable balance for a set of addresses
  # @param coin The name of the coin i.e. bitcoin
  # @param addresses A comma seperated list of public addresses
  # @param [Hash] opts the optional parameters
  # @return [Balance]
  describe 'get_balance test' do
    it "should work" do
      address_api = SwaggerClient::AddressAPIApi.new
      puts address_api.get_balance('bitcoin', '1STRonGxnFTeJiA7pgyneKknR29AwBM77')
    end
  end

end
