=begin
#ONCHAIN.IO API overview

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v2

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::TransactionAPIApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ERC20Api' do
  before do
    # run before each test
    @instance = SwaggerClient::ERC20Api.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TransactionAPIApi' do
    it 'should create an instance of TransactionAPIApi' do
      expect(@instance).to be_instance_of(SwaggerClient::ERC20Api)
    end
  end

  describe 'create an ethereum transaction' do
    it "should create an ethereum transaction" do
      
      tx = @instance.create('0x46FC2341DC457BA023cF6d60Cb0729E5928A81E6', 
        '0x46FC2341DC457BA023cF6d60Cb0729E5928A81E6', 
        1, '0x1175a66a5c3343bbf06aa818bb482ddec30858e0', 18)
      
      puts tx
      
    end
  end

  describe 'sign an ethereum transaction' do
    it "should sign an ethereum transaction" do
      
      result = @instance.sign_and_send('0x46FC2341DC457BA023cF6d60Cb0729E5928A81E6', 
        '0x46FC2341DC457BA023cF6d60Cb0729E5928A81E6', 
        1, '0x1175a66a5c3343bbf06aa818bb482ddec30858e0', 18, 
        '56182368f51dce92754fcc34ba5f7b61140e45208632f145cf9ec087a600a3a8', 
        '30a8220c206ccf565720315ff2e56c6ffc202c1d5a29afa479b7ea51cb1eb845' , 27)
      
      puts result
      
    end
  end

end
