=begin
#ONCHAIN.IO API overview

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v2

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::TransactionAPIApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'TransactionAPIApi' do
  before do
    # run before each test
    @instance = SwaggerClient::TransactionAPIApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TransactionAPIApi' do
    it 'should create an instance of TransactionAPIApi' do
      expect(@instance).to be_instance_of(SwaggerClient::TransactionAPIApi)
    end
  end

  # unit tests for send_tx
  # Send Transaction
  # Send a transaction onto the network.
  # @param coin The name of the coin i.e. bitcoin
  # @param rawtx The raw signed transaction as a hex string
  # @param [Hash] opts the optional parameters
  # @return [InlineResponseDefault]
  describe 'send_tx test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
