=begin
#ONCHAIN.IO API overview

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v2

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::Addresses
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'Addresses' do
  before do
    # run before each test
    @instance = SwaggerClient::Addresses.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of Addresses' do
    it 'should create an instance of Addresses' do
      expect(@instance).to be_instance_of(SwaggerClient::Addresses)
    end
  end
end

