=begin
#<enter your title>

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 0.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::Coin
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'Coin' do
  before do
    # run before each test
    @instance = SwaggerClient::Coin.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of Coin' do
    it 'should create an instance of Coin' do
      expect(@instance).to be_instance_of(SwaggerClient::Coin)
    end
  end
end

