=begin
#ONCHAIN.IO API overview

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v2

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'date'

module SwaggerClient
  class Coin
    
    BITCOIN = "bitcoin".freeze
    LITECOIN = "litecoin".freeze
    ETHEREUM = "ethereum".freeze
    BITCOIN_PRIVATE = "bitcoin_private".freeze
    BITCOIN_GOLD = "bitcoin_gold".freeze
    DASH = "dash".freeze
    ZCASH = "zcash".freeze
    ZCLASSIC = "zclassic".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = Coin.constants.select{|c| Coin::const_get(c) == value}
      raise "Invalid ENUM value #{value} for class #Coin" if constantValues.empty?
      value
    end
  end

end
